#theme: jekyll-theme-minimal
title: Documentation for ConsoleArena
description: This site intents to serve as a documentation of the school project "ConsoleArena"
logo: /docs/img/console-arena-social.png
